### ISSUE TITLE
This is a simple, difficult to use, and useless project

### ISSUE THREAD

**Issue by weyeahh** [Whirity404/PMSL#1]
This is a simple, difficult to use, and useless project
Dette er et simpelt, svært at bruge og ubrugeligt projekt
Este es un proyecto humilde, difícil de usar e inútil.
C'est un projet humble et inutile
Это простой и бесполезный проект.

**Comment by Whirity404** [comment]
Ah, this project is a bit useless in some ways, but it has a lower footprint than some Minecraft server management software, usually around 20mb

**Comment by weyeahh** [comment]
Generally, in Minecraft server usage scenarios, space consumption is not the primary consideration. The storage space for a Minecraft server increases exponentially when active. For instance, my Minecraft server started with just 9GB, and now it nears 30GB. The decrease of a dozen MB or so has negligible impact. Server administrators prioritize the program's ease of use over space consumption, as seen in web applications. Thank you.

**Comment by Whirity404** [comment]
I mean, in the case of the vanilla GUI interface, you usually need a console window followed by a jar built-in gui window. This program simplifies the GUI window and brings the Console into the program, making it easier to manage the server.

**Comment by weyeahh** [comment]
Could you highlight any advantages of your program over the original GUI, apart from space occupation? (Actually, your program doesn't have a space occupation advantage over the original GUI either, since it's embedded in the jar and cannot be deleted to save space.)

**Comment by Whirity404** [comment]
Ah,my gui can run ever command,and can set Max Menory,Min Memory.It can custom java,Newcomer friendly

**Comment by weyeahh** [comment]
Even true beginners will not have channels to find your project, and your GUI is not very user-friendly for beginners

**Comment by Whirity404** [comment]
why it's not user-friendly for beginners? It can automatically found java

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
